<%
    try{
        con.close();
    }catch(Exception exc){
        
    }
%>
